# ./serverless.yml
service: serverless-typescript-template

plugins:
  - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-offline # used for local execution

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage}
  timeout: 30   # repository wide Lambda timeout
  environment:  # repository wide Lambda env variables
    STAGE: ${self:provider.stage}

custom:
  customVariable1: Hello, World!

functions:
  # Serverless Framework specific syntax
  Function1:
    handler: ./src/lambda.handler
    events:
      - httpApi:
          path: /api/Function1
          method: GET
    environment:
      CUSTOM_VAR: ${self:custom.customVariable1}